### PR TITLE
Remove LazyHash, use symbol hash keys in choices hash

### PR DESCRIPTION
**Pull request by foucist**
Wouldn't it be nice to simplify the Choice codebase and standardize on symbol-based hash keys?

P.S. This isn't an entirely serious PR, as I'm sure there's philosophical differences about it.  I'm just feeling the waters. :)

### CODE REVIEW

**Comment by gaustin** [comment]
Actually, I despise so called "indifferent access". Removing LazyHash has been on my todo list for a long time.

Any ideas why this fails on Ruby 1.9.3 and 2.1?

**Comment by foucist** [comment]
Seems to be a known issue with travis-ci using an outdated bundler version.

https://github.com/travis-ci/travis-ci/issues/3531

So I added 
```
before_install:
  - gem install bundler
```
to .travis.yml to fix it.

**Comment by gaustin** [comment]
Thanks!

**Comment by foucist** [comment]
Cool! :)

**Pull request merged**
